// Builds the showcase's media: every clip's frames at 512 px (crisp, a quarter
// of the mod's 1024 px, plenty for a 1080p video) as media/<clip>-f<n>.png, the
// title slabs in the mod's own arcade lettering as media/title-<name>.png, and
// the logo. fframes embeds only the top level of media/, keyed by file name,
// hence the flat layout and the unique names. Run from the repo:
// node showcase/tools/media.mjs
import { writeFileSync, readdirSync, unlinkSync, copyFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { encodePNG, upscale } from '../../tools/png.mjs'
import { CLIPS, SIZE, Canvas, renderFrame, drawTitle } from '../../hooks/pixi.js'
import { HEAD_ROWS, HEAD_PALETTE } from '../../hooks/head.js'
import { drawStoryLayers, STORY_FRAMES, W as STORY_W, H as STORY_H } from './story.mjs'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url))) // showcase/
const REPO = dirname(ROOT)
const SCALE = 4

const MEDIA = join(ROOT, 'media')
// start clean: everything generated is a PNG; the fonts stay
for (const f of readdirSync(MEDIA)) if (f.endsWith('.png')) unlinkSync(join(MEDIA, f))
for (const clip of CLIPS) {
  for (let i = 0; i < clip.frames; i++) {
    const { canvas } = renderFrame(clip, i)
    writeFileSync(join(MEDIA, `${clip.id}-f${i}.png`), encodePNG(upscale(canvas.rgba, SIZE, SIZE, SCALE), SIZE * SCALE, SIZE * SCALE))
  }
  console.log(`${clip.id}: ${clip.frames} frames`)
}

// The story, at its own 240 x 135 (the video scales it by exactly 8), as two
// layers a frame: the room (bg) and the furniture with Pixi (fg), for parallax.
const phone = []
for (let i = 0; i < STORY_FRAMES; i++) {
  const { bg, fg, joints } = drawStoryLayers(i)
  if (!joints.reached) console.log(`story f${i}: an IK target is out of reach`)
  if (joints.phone) phone.push(`    (${i}, ${joints.phone[0].toFixed(1)}, ${joints.phone[1].toFixed(1)}),`)
  writeFileSync(join(MEDIA, `bg-f${i}.png`), encodePNG(bg.rgba, STORY_W, STORY_H))
  writeFileSync(join(MEDIA, `fg-f${i}.png`), encodePNG(fg.rgba, STORY_W, STORY_H))
}
writeFileSync(join(ROOT, 'src', 'phone.rs'), `//! Generated by tools/media.mjs: the centre of the phone's screen (story frame, x, y in the room's 240 x 135 px) while Pixi holds it.\npub const PHONE: &[(usize, f32, f32)] = &[\n${phone.join('\n')}\n];\n`)
console.log(`story: ${STORY_FRAMES} frames`)

// Title slabs on a transparent canvas, sized to the text, at 2x in the font then 4x in pixels.
// the slab palettes: face, lit band, extruded side
const PALETTES = {
  gold: {},
  cream: { face: 0xf1e9ff, lit: 0xffffff, side: 0x9c90c4 },
  blue: { face: 0x69a8bd, lit: 0xa9dcf5, side: 0x2f5f74 },
  pink: { face: 0xe86a8a, lit: 0xffb0c4, side: 0x8c2f4c },
  cyan: { face: 0x48c1c5, lit: 0xb5f4f6, side: 0x1f6f78 }, // Pixi's hair: the keyword colour
}
function slab(name, lines, s = 2) {
  const w = Math.max(...lines.map((l) => l.length)) * 6 * s + 16, h = lines.length * 9 * s + 16
  for (const [pal, opts] of Object.entries(PALETTES)) {
    const cv = new Canvas(w, h)
    drawTitle(cv, lines, w / 2, h / 2, s, opts)
    writeFileSync(join(MEDIA, `title-${name}-${pal}.png`), encodePNG(upscale(cv.rgba, w, h, SCALE), w * SCALE, h * SCALE))
  }
  console.log(`title ${name}: ${w}x${h}`)
}
// every caption of the video, as a slab; '|' breaks a line. Sizes go to src/slabs.rs.
const CAPTIONS = {
  'pumpt': 'PUMPT!',
  'get-pumpt': 'GET PUMPT!',
  'good-job': 'GOOD JOB!',
  'ready': 'READY?',
  'this-is-pixi': 'THIS IS PIXI.',
  'prompts': 'PIXI PROMPTS CLAUDE ALL DAY.',
  'takes': 'CLAUDE TAKES A WHILE…',
  'waits': '…SO PIXI WAITS.',
  'on-x': 'ON Ｘ.',
  'on': 'ON',
  'dot': '.',
  'bang': '!',
  'every': 'EVERY.',
  'single': 'SINGLE.',
  'prompt': 'PROMPT.',
  'hmm': 'HMM.',
  'waiting': 'ALL THAT WAITING…',
  'workout': '…COULD BE A WORKOUT.',
  'built': 'SO PIXI BUILT|HIMSELF A GYM.',
  'inside': 'INSIDE THE TERMINAL.',
  'system-one': 'SYSTEM ONE',
  'one-pass': 'ONE FORWARD PASS.|NO CHAIN OF THOUGHT.',
  'probability': 'A PROBABILITY|FOR EVERY LEVEL.',
  'top-pick': 'TOP PICK WINS:|SQUATS, 72%',
  'above': 'RIGHT ABOVE|YOUR PROMPT.',
  'hillclimb': 'IT HILLCLIMBS.|SHARPER EVERY TURN.',
  'you-prompt': 'YOU PROMPT CLAUDE.',
  'reads': 'A SYSTEM ONE MODEL|READS THE PROMPT…',
  'estimates': '…AND ESTIMATES HOW|HARD THE JOB IS.',
  'top-prob': 'TOP PROBABILITY:|LEVEL 5, 72%',
  'so-squats': '…SO PIXI DOES SQUATS.',
  'learns': 'EVERY TURN IT LOGS,|IT LEARNS.',
  'local2': 'ALL OF IT LOCAL.|YOUR MAC. NO CLOUD.',
  // the parts of the captions with a keyword, laid out by lib.rs's `rich`
  'it': 'IT',
  'hillclimbs': 'HILLCLIMBS.',
  'sharper': 'SHARPER EVERY TURN.',
  'a': 'A',
  'model': 'MODEL',
  'reads2': 'READS THE PROMPT…',
  'all-of-it': 'ALL OF IT',
  'local-kw': 'LOCAL.',
  'mac': 'YOUR MAC. NO CLOUD.',
  'so-pixi-does': '…SO PIXI DOES',
  'squats-kw': 'SQUATS.',
  'top-probability': 'TOP PROBABILITY:',
  'level5': 'LEVEL 5,',
  'pct72': '72%',
  'plateau': '81%',
  'thats-new': "THAT'S NEW.",
  'accuracy': 'ACCURACY',
  'turns': 'TURNS LOGGED',
  'easy': 'EASY PROMPT: NECK ROLLS.',
  'big': 'BIG PROMPT: BURPEES!',
  'now': 'NOW, WHEN CLAUDE WORKS…',
  'pixi-works': '…PIXI WORKS OUT.',
  'bye': 'BYE, BELLY.',
  'excuses': 'SAME TIME.|ZERO EXCUSES.',
  'finish': 'FINISH THE SET.|TAKE A BOW.',
  'local': '100% LOCAL · OPEN SOURCE',
  'pct-local': '100% LOCAL',
  'open-source': 'OPEN SOURCE',
  'url': 'GITHUB.COM/PANOPLOS/PUMPT',
}
const sizes = []
for (const [key, text] of Object.entries(CAPTIONS)) {
  const lines = text.split('|')
  const w = Math.max(...lines.map((l) => l.length)) * 6 * 2 + 16, h = lines.length * 9 * 2 + 16
  slab(key, lines)
  sizes.push(`    ("${key}", ${w * SCALE}., ${h * SCALE}.),`)
}
for (const n of ['1', '2', '3', '4', '5', '6', '7']) {
  slab(`level-${n}`, [n], 2)
  sizes.push(`    ("level-${n}", ${(6 * 2 + 16) * SCALE}., ${(9 * 2 + 16) * SCALE}.),`)
}
writeFileSync(join(ROOT, 'src', 'slabs.rs'), `//! Generated by tools/media.mjs: the caption slabs (media/title-<name>.png) and their sizes in PNG pixels, 4 per art pixel.\npub const SLABS: &[(&str, f32, f32)] = &[\n${sizes.join('\n')}\n];\n`)
copyFileSync(join(REPO, 'tools', 'pixi-logo.png'), join(MEDIA, 'pixi-logo.png'))

// Pixi's head alone (the logo's wordmark is not on its pixel grid and smears when scaled): 50 x 44 cells at 8 px.
{
  const w = HEAD_ROWS[0].length, h = HEAD_ROWS.length
  const cv = new Canvas(w, h)
  HEAD_ROWS.forEach((row, y) => {
    for (let x = 0; x < w; x++) if (row[x] !== '.') cv.set(x, y, parseInt(HEAD_PALETTE[row[x]].slice(1), 16))
  })
  writeFileSync(join(MEDIA, 'pixi-head.png'), encodePNG(upscale(cv.rgba, w, h, 8), w * 8, h * 8))
  console.log(`pixi-head: ${w * 8}x${h * 8}`)
}
