// Lifts Pixi's head out of tools/pixi-logo.png (an 8 px pixel-art grid) into
// hooks/head.js: a palette plus one string per row, one character per pixel.
// Usage: node tools/extract-head.mjs
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const BLOCK = 8 // logo pixels per art pixel
const HEAD_ROWS = 44 // rows 44+ hold the "Pixi" wordmark

const bmp = join(mkdtempSync(join(tmpdir(), 'pixi-')), 'logo.bmp')
execFileSync('sips', ['-s', 'format', 'bmp', join(ROOT, 'tools', 'pixi-logo.png'), '--out', bmp], { stdio: 'pipe' })
const buf = readFileSync(bmp)
const offset = buf.readUInt32LE(10)
const width = buf.readInt32LE(18)
const height = buf.readInt32LE(22)
const bytes = buf.readUInt16LE(28) / 8
const rowSize = Math.ceil((width * bytes) / 4) * 4
const h = Math.abs(height)
const px = (x, y) => {
  const o = offset + (height > 0 ? h - 1 - y : y) * rowSize + x * bytes
  return [buf[o + 2], buf[o + 1], buf[o], bytes === 4 ? buf[o + 3] : 255]
}

// Average each 8x8 block's inner 6x6 (the edges carry resampling noise).
const W = width / BLOCK
const cells = []
for (let y = 0; y < HEAD_ROWS; y++) {
  for (let x = 0; x < W; x++) {
    let r = 0, g = 0, b = 0, a = 0, n = 0
    for (let dy = 1; dy < BLOCK - 1; dy++)
      for (let dx = 1; dx < BLOCK - 1; dx++) {
        const c = px(x * BLOCK + dx, y * BLOCK + dy)
        r += c[0]; g += c[1]; b += c[2]; a += c[3]; n++
      }
    cells.push(a / n < 128 ? null : [r / n, g / n, b / n])
  }
}

// Cluster colors: greedy, nearest existing center within a tolerance.
const TOL = 34
const centers = [] // { sum: [r,g,b], n }
const index = cells.map((c) => {
  if (!c) return -1
  let best = -1, bd = Infinity
  centers.forEach((k, i) => {
    const m = k.sum.map((v) => v / k.n)
    const d = Math.hypot(c[0] - m[0], c[1] - m[1], c[2] - m[2])
    if (d < bd) { bd = d; best = i }
  })
  if (best < 0 || bd > TOL) { centers.push({ sum: [...c], n: 1 }); return centers.length - 1 }
  const k = centers[best]
  k.sum = k.sum.map((v, i) => v + c[i]); k.n++
  return best
})
const order = centers.map((k, i) => i).sort((a, b) => centers[b].n - centers[a].n)
const CHARS = 'OTSBPYDKGWLNMEFHIJQRUVXZabcdefghijklmnopqrstuvwxyz0123456789'
const remap = new Map(order.map((i, rank) => [i, rank]))
const palette = order.map((i) => {
  const m = centers[i].sum.map((v) => Math.round(v / centers[i].n))
  return '#' + m.map((v) => v.toString(16).padStart(2, '0')).join('')
})
if (palette.length > CHARS.length) throw new Error(`${palette.length} colors, only ${CHARS.length} characters`)
const rows = []
for (let y = 0; y < HEAD_ROWS; y++) rows.push(index.slice(y * W, (y + 1) * W).map((i) => (i < 0 ? '.' : CHARS[remap.get(i)])).join(''))

// Trim empty columns/rows.
let x0 = W, x1 = 0, y0 = HEAD_ROWS, y1 = 0
rows.forEach((r, y) => { for (let x = 0; x < W; x++) if (r[x] !== '.') { x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y) } })
const trimmed = rows.slice(y0, y1 + 1).map((r) => r.slice(x0, x1 + 1))

const out =
  `// Generated by tools/extract-head.mjs from tools/pixi-logo.png — do not edit.\n` +
  `// Pixi's head at the logo's native pixel grid, ${trimmed[0].length}x${trimmed.length}; '.' is transparent.\n` +
  `export const HEAD_PALETTE = ${JSON.stringify(Object.fromEntries(palette.map((c, i) => [CHARS[i], c])), null, 0)}\n` +
  `export const HEAD_ROWS = [\n${trimmed.map((r) => `  '${r}',`).join('\n')}\n]\n`
writeFileSync(join(ROOT, 'hooks', 'head.js'), out)
console.log(`head ${trimmed[0].length}x${trimmed.length}, ${palette.length} colors:`, palette.join(' '))
console.log(trimmed.join('\n'))
